name: Github Action Build PKGBUILD
on: push
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        run: |
          /lib/ld-linux-x86-64.so.2 --help | grep "x86-64-v"
