name: Github Action Build PKGBUILD
on: push
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        uses: antman666/build-aur-action@mine
        with:
          repo-name: linux-ck-uksm
      - uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "linux-ck-uksm_v6.1.0-1"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
